sudo: required

language: node_js

node_js:
  - "node"

services:
  - docker

before_install:
  - sudo apt-get update && sudo apt-get install -y python3-pip
  - pip3 list
  - sudo pip3 install ansible
  - ls
  - ansible-playbook ./tools/install-all.yml
  - npm install
  - npm run build

script:
  - cucumber-js test
