sudo: required

language: node_js

node_js:
  - "node"

services:
  - docker

before_install:
  - apt-get update && apt-get install -y curl
  - npm install
  - npm run build

script:
  - cucumber-js test
